#!/usr/bin/env php
<?php
/**
 * Fetch old cpp-globez.ru service pages and prepare WP `services` imports.
 *
 * Usage (from machine with PHP + curl):
 *   php scripts/import-cpp-globez-services.php
 *
 * Outputs:
 *   scripts/import-artifacts/<slug>.content.html
 *   scripts/import-artifacts/<slug>.title.txt
 *   scripts/import-artifacts/wp-cli-import.sh  (run from WordPress root where `wp` works)
 *
 * @package CppCoursesTheme
 */

$root = dirname(__DIR__);
$url_file = $root . '/scripts/import-services-urls.txt';
$out_dir = $root . '/scripts/import-artifacts';

$content_class_candidates = array(
    'security-training',
    'cpp-training',
    'chief-security-training',
    'training-section',
    'exam-faq',
    'cpp-shooting',
    'collector-course',
    // Fallbacks seen on old layout (lower priority after specific blocks).
    'uk-margin',
);

if (!is_readable($url_file)) {
    fwrite(STDERR, "Missing URL list: {$url_file}\n");
    exit(1);
}

if (!is_dir($out_dir)) {
    mkdir($out_dir, 0755, true);
}

$urls = array();
foreach (file($url_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
    $line = trim($line);
    if ($line === '' || (isset($line[0]) && $line[0] === '#')) {
        continue;
    }
    $urls[$line] = true;
}
$urls = array_keys($urls);

$sh_lines = array(
    '#!/usr/bin/env bash',
    '# Generated by import-cpp-globez-services.php — run from WordPress root (directory containing wp-cli.yml or wp-load.php)',
    'set -euo pipefail',
    '',
);

foreach ($urls as $url) {
    $path = parse_url($url, PHP_URL_PATH);
    if (!$path || $path === '/') {
        fwrite(STDERR, "Skip (no path): {$url}\n");
        continue;
    }
    $slug = trim($path, '/');
    if ($slug === '') {
        fwrite(STDERR, "Skip (empty slug): {$url}\n");
        continue;
    }

    echo "Fetching {$url} …\n";
    $html = http_get($url);
    if ($html === '') {
        fwrite(STDERR, "  FAILED empty response\n");
        continue;
    }

    $dom = new DOMDocument();
    libxml_use_internal_errors(true);
    $loaded = $dom->loadHTML('<?xml encoding="UTF-8">' . $html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
    libxml_clear_errors();
    if (!$loaded) {
        fwrite(STDERR, "  FAILED parse HTML\n");
        continue;
    }

    $xp = new DOMXPath($dom);
    $title = extract_first_h1_text($dom, $xp);
    if ($title === '') {
        $title = $slug;
    }

    $node = find_content_node($xp, $content_class_candidates);
    if (!$node) {
        fwrite(STDERR, "  WARN no content block for classes: " . implode(', ', $content_class_candidates) . "\n");
        $inner = '';
    } else {
        $inner = inner_html($dom, $node);
    }

    file_put_contents($out_dir . '/' . $slug . '.title.txt', $title);
    file_put_contents($out_dir . '/' . $slug . '.content.html', $inner);

    $title_esc = escapeshellarg($title);
    $content_file = $out_dir . '/' . $slug . '.content.html';
    $content_esc = escapeshellarg($content_file);

    $sh_lines[] = "echo 'Import services: {$slug}'";
    $sh_lines[] = sprintf(
        'wp post create %s --post_type=services --post_status=publish --post_name=%s --post_title=%s --porcelain',
        $content_esc,
        escapeshellarg($slug),
        $title_esc
    );
    $sh_lines[] = '';
}

file_put_contents($out_dir . '/wp-cli-import.sh', implode("\n", $sh_lines) . "\n");
chmod($out_dir . '/wp-cli-import.sh', 0755);

echo "\nDone. Artifacts in: {$out_dir}\n";
echo "Review HTML files, then run: bash scripts/import-artifacts/wp-cli-import.sh\n";
exit(0);

/**
 * @return string
 */
function http_get($url) {
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array(
            $ch,
            array(
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => true,
                CURLOPT_TIMEOUT => 60,
                CURLOPT_USERAGENT => 'CppGlobezImporter/1.0 (+https://cpp-globez.ru)',
                CURLOPT_SSL_VERIFYPEER => true,
            )
        );
        $body = curl_exec($ch);
        $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($code < 200 || $code >= 400 || !is_string($body)) {
            return '';
        }
        return $body;
    }
    $ctx = stream_context_create(
        array(
            'http' => array(
                'timeout' => 60,
                'user_agent' => 'CppGlobezImporter/1.0',
                'follow_location' => 1,
            ),
        )
    );
    $body = @file_get_contents($url, false, $ctx);
    return is_string($body) ? $body : '';
}

/**
 * @param DOMXPath $xp
 * @param string[] $class_names
 * @return DOMElement|null
 */
function find_content_node(DOMXPath $xp, array $class_names) {
    foreach ($class_names as $cn) {
        $cn = preg_replace('/[^a-zA-Z0-9_-]/', '', $cn);
        if ($cn === '') {
            continue;
        }
        // Match element whose class list contains $cn as a whole token.
        $q = "//*[contains(concat(' ', normalize-space(@class), ' '), ' {$cn} ')]";
        $nodes = $xp->query($q);
        if ($nodes && $nodes->length > 0) {
            /** @var DOMElement $el */
            $el = $nodes->item(0);
            return $el;
        }
    }
    return null;
}

/**
 * @return string
 */
function extract_first_h1_text(DOMDocument $dom, DOMXPath $xp) {
    $nodes = $xp->query('//h1');
    if (!$nodes || $nodes->length === 0) {
        return '';
    }
    return trim($nodes->item(0)->textContent);
}

/**
 * @return string
 */
function inner_html(DOMDocument $dom, DOMNode $node) {
    $html = '';
    foreach ($node->childNodes as $child) {
        $html .= $dom->saveHTML($child);
    }
    return $html;
}
