#!/usr/bin/env python3
"""Fetch cpp-globez.ru service pages and write WP-CLI import artifacts."""

from __future__ import annotations

import shlex
import sys
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parent.parent
URL_FILE = ROOT / "scripts" / "import-services-urls.txt"
OUT_DIR = ROOT / "scripts" / "import-artifacts"

CONTENT_CLASSES = [
    "security-training",
    "cpp-training",
    "chief-security-training",
    "training-section",
    "exam-faq",
    "cpp-shooting",
    "collector-course",
    "uk-margin",
]

UA = "CppGlobezImporter/1.0 (+https://cpp-globez.ru)"


def fetch(url: str) -> str:
    req = Request(url, headers={"User-Agent": UA})
    with urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8", errors="replace")


def main() -> int:
    if not URL_FILE.is_file():
        print(f"Missing {URL_FILE}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    urls: list[str] = []
    seen: set[str] = set()
    for line in URL_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line not in seen:
            seen.add(line)
            urls.append(line)

    sh_lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Generated by import-cpp-globez-services.py",
        "set -euo pipefail",
        "",
    ]

    for url in urls:
        path = urlparse(url).path or ""
        slug = path.strip("/").split("/")[-1] if path.strip("/") else ""
        if not slug:
            print(f"Skip (no slug): {url}", file=sys.stderr)
            continue

        print(f"Fetching {url} …")
        try:
            html = fetch(url)
        except Exception as exc:
            print(f"  FAILED {exc}", file=sys.stderr)
            continue

        soup = BeautifulSoup(html, "html.parser")
        h1 = soup.find("h1")
        title = h1.get_text(strip=True) if h1 else slug

        inner = ""
        for cn in CONTENT_CLASSES:
            el = soup.select_one(f".{cn}")
            if el:
                inner = el.decode_contents()
                break

        if not inner.strip():
            print(
                f"  WARN no block for: {', '.join(CONTENT_CLASSES)}",
                file=sys.stderr,
            )

        (OUT_DIR / f"{slug}.title.txt").write_text(title, encoding="utf-8")
        (OUT_DIR / f"{slug}.content.html").write_text(inner, encoding="utf-8")

        content_file = OUT_DIR / f"{slug}.content.html"
        cmd = (
            "wp post create "
            + shlex.quote(str(content_file))
            + " --post_type=services --post_status=publish "
            + f"--post_name={shlex.quote(slug)} --post_title={shlex.quote(title)} --porcelain"
        )
        sh_lines.append(f"echo 'Import services: {slug}'")
        sh_lines.append(cmd)
        sh_lines.append("")

    sh_path = OUT_DIR / "wp-cli-import.sh"
    sh_path.write_text("\n".join(sh_lines) + "\n", encoding="utf-8")
    sh_path.chmod(0o755)

    print(f"\nDone. Artifacts: {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
